# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

# Gemの並び順は任意にする
Bundler/OrderedGems:
  Enabled: false

# 一行の長さは100字まで。コメントは制限しない
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']
  Exclude:
    - "config/initializers/*"

# ABC sizeは緩めにする
Metrics/AbcSize:
  Max: 30 # default 15

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/development.rb"

# メソッドの行数を20行までにする
Metrics/MethodLength:
  CountComments: false
  Max: 20

# コントローラのみメソッド名に「set_」「get_」を許可
Naming/AccessorMethodName:
  Exclude:
    - "app/controllers/**/*"

Rails/HasManyOrHasOneDependent:
  Exclude:
    # ActiveHashのhas_manyはdependent不要なので
    - "app/models/product_type.rb"
    - "app/models/social_service.rb"
    - "app/models/product_category.rb"

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# Admin::BaseControllerのような書き方を許可
Style/ClassAndModuleChildren:
  Enabled: false

# frozen_string_literal: trueはなくていい
Style/FrozenStringLiteralComment:
  Enabled: false

# each_key, value, transform_keys, valueを使用する
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false
