version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

executors:
  default_executor:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 2.2.3
          TZ: "Japan"
      - image: circleci/mysql:8.0.19-ram
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_USER: root
          MYSQL_DB: circle_test

commands:
  check_versions:
    steps:
      - run: bundle -v
      - run: node -v
      - run: yarn -v

  setup_bundler:
    steps:
      - run:
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo gem install bundler
      - run:
          name: bundle install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

  setup_database:
    steps:
      - run:
          name: wait for database
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m
      - run:
          name: cp database.yml
          command: |
            cp -v config/database.ci.yml config/database.yml
      - run: mysql_config --socket
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

  setup_yarn:
    steps:
      - run: yarn install

  # Build JavaScript files （eslintも実行する）
  build_webpack:
    steps:
      - run: bundle exec bin/webpack

  run_lint:
    steps:
      - run: bundle exec rails factory_bot:lint RAILS_ENV=test
      - run: bundle exec rubocop
      - run: bundle exec brakeman

  run_tests:
    steps:
      - run:
          name: eager_load test
          command: bundle exec rails runner Rails.application.eager_load!
      - run:
          name: run rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

  # steps:
  #   - checkout

  # - run:
  #     name: wait for database
  #     command: dockerize -wait tcp://127.0.0.1:3306 -timeout 3m

  # まだ↓
  # Restore bundle cache
  # - restore_cache:
  #     keys:
  #       - rails-demo-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
  #       - rails-demo-

  # - run:
  #     name: setup bundler
  #     command: |
  #       sudo gem update --system
  #       sudo gem uninstall bundler
  #       sudo rm /usr/local/bin/bundle
  #       sudo gem install bundler
  # - run:
  #     name: Which bundler?
  #     command: bundle -v

  # - run:
  #     name: bundle install
  #     command: |
  #       bundle install --jobs=4 --retry=3 --path vendor/bundle

  # Store bundle cache
  # まだ↓
  # - save_cache:
  #     paths:
  #       - ./vendor/bundle
  #       - ./node_modules
  #     key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

  # - run:
  #     name: setup database
  #     command: |
  #       cp -v config/database.ci.yml config/database.yml
  # - run: mysql_config --socket
  # - run: bundle exec rails db:create
  # - run: bundle exec rails db:schema:load

  # - run:
  #     name: eager_load test
  #     command: bundle exec rails runner Rails.application.eager_load!

  # - run: bundle exec rails factory_bot:lint RAILS_ENV=test
  # - run: bundle exec rubocop
  # - run: bundle exec brakeman

  # - run:
  #     name: run rspec
  #     command: |
  #       bundle exec rspec --profile 10 \
  #                         --format RspecJunitFormatter \
  #                         --out test_results/rspec.xml \
  #                         --format progress \
  #                         $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

jobs:
  setup:
    executor: default_executor
    steps:
      - checkout
      - setup_bundler
      - setup_yarn
      - check_versions
  lint:
    executor: default_executor
    steps:
      - checkout
      - setup_yarn
      - build_webpack
      - run_lint
  test:
    executor: default_executor
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - setup_bundler
      - setup_database
      - setup_yarn
      - build_webpack
      - run_tests

workflows:
  version: 2

  commit:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
